============================= test session starts ==============================
platform darwin -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0 -- /opt/anaconda3/bin/python
cachedir: .pytest_cache
rootdir: /Users/sruthibhaskar/SRUUUUU/Big Data Systems and Intelligence Analytics/Final_Draft_Assignment1/DAMG_7245/Assignment1
plugins: anyio-3.5.0
collecting ... collected 12 items

testing_nexrad.py::test_01 PASSED                                        [  8%]
testing_nexrad.py::test_02 PASSED                                        [ 16%]
testing_nexrad.py::test_03 PASSED                                        [ 25%]
testing_nexrad.py::test_04 PASSED                                        [ 33%]
testing_nexrad.py::test_05 PASSED                                        [ 41%]
testing_nexrad.py::test_06 FAILED                                        [ 50%]
testing_nexrad.py::test_07 PASSED                                        [ 58%]
testing_nexrad.py::test_08 PASSED                                        [ 66%]
testing_nexrad.py::test_09 PASSED                                        [ 75%]
testing_nexrad.py::test_10 PASSED                                        [ 83%]
testing_nexrad.py::test_11 PASSED                                        [ 91%]
testing_nexrad.py::test_12 PASSED                                        [100%]

=================================== FAILURES ===================================
___________________________________ test_06 ____________________________________

    def test_06():
>       assert file_URL("KCBW20011213_002358.gz")==""
E       AssertionError: assert 'https://noaa...213_002358.gz' == ''
E         + https://noaa-nexrad-level2.s3.amazonaws.com/2001/12/13/KCBW/KCBW20011213_002358.gz

testing_nexrad.py:29: AssertionError
=========================== short test summary info ============================
FAILED testing_nexrad.py::test_06 - AssertionError: assert 'https://noaa...21...
========================= 1 failed, 11 passed in 0.05s =========================
